//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Đồ_án_II
{
    using System;
    using System.Collections.Generic;
    
    public partial class xetonkho
    {
        public string MaXe { get; set; }
        public string TenXe { get; set; }
        public string Maloaixe { get; set; }
        public string MaNCC { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
        public string SoKhung { get; set; }
        public string SoMay { get; set; }
        public string Mau { get; set; }
        public string Dungtich { get; set; }
        public string TinhTrang { get; set; }
    }
}
